name: Webscan  # Name of the GitHub Actions workflow

on:  # Define when to trigger the workflow
  push:  # Trigger the workflow on pushes to any branch
    workflow_dispatch:  # Also trigger the workflow manually via GitHub UI

jobs:  # Define jobs to be executed within the workflow
  dast_scan:  # Job named "zap_scan"
    runs-on: ubuntu-latest  # Run the job on the latest version of Ubuntu

    name: Scan the webapplication  # Name of the job

    steps:  # Define steps to be executed within the job
      - name: ZAP Scan  # Step to perform ZAP Scan
        uses: zaproxy/action-full-scan@v0.9.0  # Use ZAP Proxy action for performing a full scan
        with:
          target: 'https://teststalapotheek.nl'  # Define the target URL for the scan
      - name: Create sarif file from zaproxy results
        uses: SvanBoxel/zaproxy-to-ghas@main
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
