name: Webscan  # Name of the GitHub Actions workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  dast_scan:
    runs-on: ubuntu-latest

    name: Scan the webapplication

    steps:
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.9.0
        with:
          target: 'https://stalapotheek.nl'
          allow_issue_writing: false

      - name: Suppress email notifications
        run: |
          echo "action: 'action_triggered'" >> $GITHUB_EVENT_PATH
        if: always()

      - name: Create sarif file from zaproxy results
        uses: SvanBoxel/zaproxy-to-ghas@main

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif

