nname: Webscan  # Name of the GitHub Actions workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  dast_scan:
    runs-on: ubuntu-latest

    name: Scan the webapplication

    steps:
      - name: Install dependencies
        run: npm install @octokit/core

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.9.0
        with:
          target: 'https://teststalapotheek.nl'

      - name: Intercept and move issues to Security tab
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { Octokit } = require("@octokit/core");
            const octokit = new Octokit({ 
              auth: process.env.GITHUB_TOKEN,
              request: {
                fetch: require('node-fetch')
              }
            });

            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const { data: issues } = await octokit.request('GET /repos/{owner}/{repo}/issues', {
              owner: owner,
              repo: repo
            });

            for (const issue of issues) {
              if (issue.title.includes('ZAP Scan')) {
                await octokit.request('PATCH /repos/{owner}/{repo}/issues/{issue_number}', {
                  owner: owner,
                  repo: repo,
                  issue_number: issue.number,
                  labels: ['security']
                });
              }
            }



      # - name: Create sarif file from zaproxy results
      #   uses: SvanBoxel/zaproxy-to-ghas@main
      # - name: Upload SARIF file
      #   uses: github/codeql-action/upload-sarif@v1
      #   with:
      #     sarif_file: results.sarif
