name: Webscan  # Name of the GitHub Actions workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  dast_scan:
    runs-on: ubuntu-latest

    name: Scan the webapplication

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.9.0
        with:
          target: 'https://teststalapotheek.nl'

      - name: Generate SARIF file from ZAP Proxy results
        uses: SvanBoxel/zaproxy-to-ghas@main
        id: generate_sarif

      - name: Make Python script executable
        run: chmod +x filter.py

      - name: Filter Duplicate Entries and Combine Occurrences
        id: filter_and_combine
        run: python filter.py

      - name: Upload Combined SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: combined_results.sarif
