name: Webscan  # Name of the GitHub Actions workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  dast_scan:
    runs-on: ubuntu-latest

    name: Scan the webapplication

    steps:
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.9.0
        with:
          target: 'https://teststalapotheek.nl'

      - name: Delete issues created by ZAP Scan
        run: |
          # Install jq for JSON parsing
          sudo apt-get update && sudo apt-get install -y jq

          # Get the current repository name
          repo=$(basename "$(pwd)")

          # Get all issues in the repository
          issues=$(curl -s "https://api.github.com/repos/${GITHUB_REPOSITORY}/issues?state=all" \
              | jq -r '.[] | select(.title | test("ZAP Scan")) | .number')

          # Delete each issue
          for number in $issues; do
              curl -X DELETE \
                  "https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/$number"
          done

      - name: Suppress email notifications
        run: |
          echo "action: 'action_triggered'" >> $GITHUB_EVENT_PATH
        if: always()

      - name: Create sarif file from zaproxy results
        uses: SvanBoxel/zaproxy-to-ghas@main

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif

