name: Webscan  # Name of the GitHub Actions workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  dast_scan:
    runs-on: ubuntu-latest

    name: Scan the webapplication

    steps:
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.9.0
        with:
          target: 'https://teststalapotheek.nl'

      - name: Delete issues created by ZAP Scan
        run: |
          token=${{ secrets.GITHUB_TOKEN }}
          owner=${{ github.repository_owner }}
          repo=${{ github.event.repository.name }}
          issue_numbers=$(curl -s -H "Authorization: token $token" \
              "https://api.github.com/repos/$owner/$repo/issues?state=all" \
              | jq '.[] | select(.title | test("ZAP Scan")) | .number')

          for number in $issue_numbers; do
              curl -XDELETE -H "Authorization: token $token" \
                  "https://api.github.com/repos/$owner/$repo/issues/$number"
          done

      - name: Suppress email notifications
        run: |
          echo "action: 'action_triggered'" >> $GITHUB_EVENT_PATH

        if: always()

      - name: Create sarif file from zaproxy results
        uses: SvanBoxel/zaproxy-to-ghas@main

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
